### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by sergelogvinov** [bpg/terraform-provider-proxmox#1192]
**Describe the bug**

I think, because I have `numa{}` block in my terraform state (without device param).

```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 752 [running]:
github.com/bpg/terraform-provider-proxmox/utils.MapResourceList({0xc0005f2dd0, 0x1, 0x41d5490?}, {0x4054fb3, 0x6})
        /Users/serge/work/sergelogvinov/terraform-provider-proxmox-bpg/utils/maps.go:37 +0x136
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.VM.SuppressIfListsOfMapsAreEqualIgnoringOrderByKey.func59({0xc0000c26d0, 0xd}, {0xc000aacf88?, 0xc000557260?}, {0x4053724?, 0x4?}, 0xc00012b300)
        /Users/serge/work/sergelogvinov/terraform-provider-proxmox-bpg/proxmoxtf/structure/schema.go:157 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc00037f830, {0x43fa1e8, 0xc000557260}, {0x4053724, 0x4}, 0xc0003c2140, 0xc00012b280, {0x43ff3f0, 0xc00012b300}, 0x0)
        /Users/serge/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/schema.go:1143 +0x39d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00037f830, {0x43fa1e8, 0xc000557260}, 0xc000460820, 0xc0005a1cc0, 0xc0000fdb20, {0x4337800, 0xc00030f080}, 0x0)
        /Users/serge/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/schema.go:678 +0x332
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x43fa418?, {0x43fa1e8?, 0xc000557260?}, 0xc000460820, 0xc000557290?, {0x4337800?, 0xc00030f080?})
        /Users/serge/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:962 +0xdb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0000bfb18, {0x43fa1e8?, 0xc000557080?}, 0xc0005bcd70)
        /Users/serge/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:798 +0x996
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.PlanResourceChange({{0x4402aa0?, 0xc0000bfb18?}}, {0x43fa1e8, 0xc000557080}, 0x0?)
        /Users/serge/go/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5to6server/tf5to6server.go:188 +0x54
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).PlanResourceChange(0xc0003c0a80, {0x43fa1e8?, 0xc0005568d0?}, 0xc0005bcd20)
        /Users/serge/go/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf6muxserver/mux_server_PlanResourceChange.go:73 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).PlanResourceChange(0xc00046a000, {0x43fa1e8?, 0xc0004647b0?}, 0xc000b0a000)
        /Users/serge/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/tf6server/server.go:811 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_PlanResourceChange_Handler({0x43be9c0, 0xc00046a000}, {0x43fa1e8, 0xc0004647b0}, 0xc000235e80, 0x0)
        /Users/serge/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:500 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e7c00, {0x43fa1e8, 0xc000645da0}, {0x4400ae0, 0xc0001f0000}, 0xc000912120, 0xc0004648d0, 0x4a549e0, 0x0)
        /Users/serge/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1386 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc0000e7c00, {0x4400ae0, 0xc0001f0000}, 0xc000912120)
        /Users/serge/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1797 +0xe87
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /Users/serge/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1027 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 53
        /Users/serge/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1038 +0x125
```

```go
 
 // OrderedListFromMap generates a list from a map's values. The values are sorted based on the map's keys.
 func OrderedListFromMap(inputMap map[string]interface{}) []interface{} {
@@ -32,7 +34,11 @@ func MapResourceList(resourceList []interface{}, attrName string) map[string]int
        m := make(map[string]interface{}, len(resourceList))
 
        for _, resource := range resourceList {
-               r := resource.(map[string]interface{})
+               r, err := resource.(map[string]interface{})
+               if !err {
+                       continue
+               }
+
                key := r[attrName].(string)
                m[key] = r
        }
```

**To Reproduce**

1. Create a resource '....'
2. Run '....'
3. See error
4. Modify the resource '....'
5. Run '....'
6. See error

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl

# >>> put your example here <<< #

```

**Expected behavior**

**Screenshots**

**Additional context**

- Single or clustered Proxmox:
- Provider version (ideally it should be the latest version):
- Terraform version:
- OS (where you run Terraform from):
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by sergelogvinov** [comment]
thank you 👍
