### ISSUE TITLE
Panic crash in provider on main branch

### ISSUE THREAD

**Issue by rafsaf** [bpg/terraform-provider-proxmox#544]
**Describe the bug**
Panic error in provider, this is related to my PR https://github.com/bpg/terraform-provider-proxmox/pull/520 :P

In fact, https://github.com/bpg/terraform-provider-proxmox/pull/520#discussion_r1314023846 i think i used int32 there because of this weird crash, after change it cause panic error like below.

**To Reproduce**
1. Run `make example` on current main branch 
2. See panic error in terminal

```bash
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-proxmox plugin:

panic: interface conversion: interface {} is int, not int32

goroutine 146 [running]:
github.com/bpg/terraform-provider-proxmox/proxmoxtf/provider.providerConfigure({0xea84fa?, 0x6?}, 0xc0001fa000?)
        /home/rafsaf/projects/terraform-provider-proxmox/proxmoxtf/provider/provider.go:139 +0x166b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0xc00004eb40, {0x10206c0, 0xc0001fa000}, 0xd?)
        /home/rafsaf/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/provider.go:300 +0x1eb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ConfigureProvider(0xc000013458, {0x10206c0?, 0xc000139320?}, 0xc00029d398)
        /home/rafsaf/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/grpc_provider.go:560 +0x345
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ConfigureProvider({{0x1027730?, 0xc000013458?}}, {0x10206c0?, 0xc000139320?}, 0xc00029c258?)
        /home/rafsaf/go/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5to6server/tf5to6server.go:48 +0x182
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ConfigureProvider({0xc000320db0, 0xc0000e79a0, 0xc000320de0, 0xc000320e10, {0xc0000915e0, 0x2, 0x2}}, {0x10206c0?, 0xc0003d52f0?}, 0xc00029c258)
        /home/rafsaf/go/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf6muxserver/mux_server_ConfigureProvider.go:28 +0x172
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0xc00026f400, {0x10206c0?, 0xc0003d41e0?}, 0xc0004ba540)
        /home/rafsaf/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:530 +0x2bb
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0xe70700?, 0xc00026f400}, {0x10206c0, 0xc0003d41e0}, 0xc00041a070, 0x0)
        /home/rafsaf/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:368 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002661e0, {0x10261d0, 0xc000102d00}, 0xc000432000, 0xc0003d4cc0, 0x1619058, 0x0)
        /home/rafsaf/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xe15
google.golang.org/grpc.(*Server).handleStream(0xc0002661e0, {0x10261d0, 0xc000102d00}, 0xc000432000, 0x0)
        /home/rafsaf/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/rafsaf/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 24
        /home/rafsaf/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x165

Error: The terraform-provider-proxmox plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

make: *** [Makefile:35: example-apply] Error 1
```

Please also provide a minimal Terraform configuration that reproduces the issue.

**Expected behavior**
No panic error

**Screenshots**
.

**Additional context**
- Provider version (ideally it should be the latest version):
- Terraform version:
- OS (where you run Terraform from):
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by bpg** [comment]
Huh... That's interesting. I don't see this error in my env 😕

**Comment by rafsaf** [comment]
$ terraform -version
Terraform v1.5.6

$ go version
go version go1.21.0 linux/amd64

can there be any differences between libs versions? I think not? I'm on Ubuntu 22

**Comment by bpg** [comment]
Same, but I'm running on darwin/arm64
I guess there is a different in `int` conversion between platforms 🤔

Anyway, good catch, thanks! Sorry for introducing a bug in your PR 😅

**Comment by rafsaf** [comment]
oh, right, the thing I changed is connecting to local pve mocking main.tf in example folder:

```
provider "proxmox" {
  endpoint = var.virtual_environment_endpoint
  username = var.virtual_environment_username
  password = var.virtual_environment_password
  insecure = true
  ssh {
    agent = true
    node {
      name    = "pve"
      address = "127.0.0.1"
      port    = 222
    }
  }
}
```

`example/main.tf`

**Comment by bpg** [comment]
🤦🏼 of course...
