### ISSUE TITLE
Disk with file_id and size causes plugin panic

### ISSUE THREAD

**Issue by joek-office** [bpg/terraform-provider-proxmox#796]
**Describe the bug**
I have the problem with a ubuntu cloud image (referenced via file_id) and the size for the corresponding disk.
When no size is defined, the space of the disk is as much as in the image, then no additional software installation is possible.
When i add the size element to the disk, the vm will be created completely and is succesfully configured (with the needed size), but the plugin crashes.

Following Ressource configuration causes the plugin panic
```
+ resource "proxmox_virtual_environment_vm" "virtual-machine" {
      + acpi                    = true
      + bios                    = "ovmf"
      + boot_order              = []
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "de"
      + mac_addresses           = (known after apply)
      + machine                 = "pc"
      + migrate                 = true
      + name                    = "DE-FRA2-JOEK1"
      + network_interface_names = (known after apply)
      + node_name               = "mgmthost1"
      + on_boot                 = true
      + reboot                  = false
      + scsi_hardware           = "virtio-scsi-pci"
      + started                 = true
      + tablet_device           = true
      + template                = false
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 120
      + timeout_shutdown_vm     = 120
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
      + vm_id                   = (known after apply)

      + cpu {
          + architecture = "x86_64"
          + cores        = 2
          + hotplugged   = 0
          + numa         = false
          + sockets      = 1
          + type         = "qemu64"
          + units        = 1024
        }

      + disk {
          + cache             = "none"
          + datastore_id      = "local-zfs"
          + discard           = "ignore"
          + file_format       = (known after apply)
          + file_id           = "local:iso/jammy-server-cloudimg-amd64-disk-kvm.img"
          + interface         = "virtio0"
          + iothread          = false
          + path_in_datastore = (known after apply)
          + size              = 5
          + ssd               = false
        }

      + efi_disk {
          + datastore_id      = "local-zfs"
          + file_format       = "raw"
          + pre_enrolled_keys = true
          + type              = "4m"
        }

      + initialization {
          + datastore_id         = "local"
          + interface            = "scsi2"
          + network_data_file_id = "local:snippets/cloud-init-network.yml"
          + user_data_file_id    = "local:snippets/cloud-init-user.yml"
        }

      + memory {
          + dedicated = 4096
          + floating  = 0
          + shared    = 0
        }

      + network_device {
          + bridge      = "vmbr0"
          + enabled     = true
          + firewall    = false
          + mac_address = (known after apply)
          + model       = "virtio"
          + mtu         = 0
          + queues      = 0
          + rate_limit  = 0
          + vlan_id     = 0
        }

      + operating_system {
          + type = "l26"
        }

      + serial_device {
          + device = "socket"
        }

      + vga {
          + enabled = true
          + memory  = 16
          + type    = "serial0"
        }
    }

```

Panic Stack Trace:
```
proxmox_virtual_environment_vm.virtual-machine["DE-FRA2-JOEK1"]: Still creating... [10s elapsed]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-proxmox_v0.40.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcabf20]

goroutine 117 [running]:
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmReadCustom({0x103ed48, 0xc000718af0}, 0xc00059fd00, {0xe14960?, 0xc0005d2000?}, 0x0?, 0xc000134000, 0x424a3c?)
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:4137 +0xd160
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmRead({0x103ed48, 0xc000718af0}, 0xc00059fd00, {0xe14960?, 0xc0005d2000?})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:3789 +0x791
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmCreateStart({0x103ed48, 0xc000718af0}, 0xc00059fd00, {0xe14960?, 0xc0005d2000?})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:2997 +0x625
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmCreateCustomDisks({0x103ed48, 0xc000718af0}, 0xc00059fd00, {0xe14960?, 0xc0005d2000?})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:2951 +0x1876
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmCreateCustom({0x103ed48, 0xc000718af0}, 0x1644c40?, {0xe14960?, 0xc0005d2000?})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:2800 +0x3145
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmCreate({0x103ed48, 0xc000718af0}, 0x0?, {0xe14960, 0xc0005d2000})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:1649 +0x94
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002fd260, {0x103eca0, 0xc000157410}, 0xd?, {0xe14960, 0xc0005d2000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:778 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002fd260, {0x103eca0, 0xc000157410}, 0xc0004a96c0, 0xc00059fb80, {0xe14960, 0xc0005d2000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000c3440, {0x103eca0?, 0xc000157260?}, 0xc000594eb0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1072 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1046280?, 0xc0000c3440?}}, {0x103eca0, 0xc000157260}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:37 +0x54
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x103ecd8?, {0x103eca0?, 0xc000156f60?}, 0xc000594e60)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0001d3900, {0x103eca0?, 0xc000156300?}, 0xc000718000)
	github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:857 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xe8bde0?, 0xc0001d3900}, {0x103eca0, 0xc000156300}, 0xc00059ec00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ce1e0, {0x103eca0, 0xc000156240}, {0x1044830, 0xc0003b6820}, 0xc000237680, 0xc0003ace40, 0x1637a78, 0x0)
	google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0001ce1e0, {0x1044830, 0xc0003b6820}, 0xc000237680)
	google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.59.0/server.go:986 +0x86
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 25
	google.golang.org/grpc@v1.59.0/server.go:997 +0x145

Error: The terraform-provider-proxmox_v0.40.0 plugin crashed!
```

**Expected behavior**
no crash, normal exit of the plugin

**Additional context**
Have tested with pc and q35 machine type.

- clustered Proxmox:
- Provider version (ideally it should be the latest version): 0.40.0
- Terraform version: v1.4.6
- OS (where you run Terraform from): alpine linux in docker container
- Debug logs (`TF_LOG=DEBUG terraform apply`): attached
[terraform proxmox provider.log](https://github.com/bpg/terraform-provider-proxmox/files/13657217/terraform.proxmox.provider.log)

**Comment by bpg** [comment]
Hi @joek-office! 👋🏼 

Thanks for the report, and I **really** appreciate the debug log.

It seems that the cloudinit "cdrom" on scsi2 is causing issues: `"scsi2": "local:131/vm-131-cloudinit.qcow2,media=cdrom"`. The provider fails to detect it as a cloudinit device, treating it as a disk drive and expecting the size attribute to be present. I believe the `.qcow2` extension of the cloud init file is causing [the detection issue](https://github.com/bpg/terraform-provider-proxmox/blob/v0.40.0/proxmoxtf/resource/vm.go#L4092-L4094).

You might want to try moving the cloud init to `local-zfs` storage; this should produce a cloud init device ID like `local-zfs:131/vm-131-cloudinit`, which _should_ work with the current provider.

Nevertheless, this logic needs to be fixed.

**Comment by bpg** [comment]
@all-contributors please add @joek-office for bug

**Comment by joek-office** [comment]
Beside of testing the described workaround, isnt it possible to add a data field for definition of cloud init file format?
Proxmox gives the option on manual creation for raw/qcow2/vmdk.

**Comment by joek-office** [comment]
> You might want to try moving the cloud init to `local-zfs` storage; this should produce a cloud init device ID like `local-zfs:131/vm-131-cloudinit`, which _should_ work with the current provider.

This fixes the problem for me. Thank you for the suggestion. 
Dont know why i have at least placed the file at this location. probably because snippets for cloudinit files are not possible on local-zfs. Never mind.

Should i close this issue at this moment or leave open for the logic fix?

**Comment by bpg** [comment]
Thanks for confirming. Let's keep the issue open for a future fix.
