### ISSUE TITLE
CloudInit drive interface on SATA crashes plugin

### ISSUE THREAD

**Issue by edwarddijk** [bpg/terraform-provider-proxmox#815]
**Describe the bug**
When you select a sata[n] interface in the initialization block for your cloudinit drive the plugin crashes with the following error:

Error: Plugin did not respond
 
The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

**To Reproduce**

1. Create a initialization configuration block in your config and set the interface parameter to sata[n]

```hcl
initialization {
    interface = "sata0"
}

```

**Expected behavior**
A  successful deployment.

**Additional context**

- Single or clustered Proxmox: Single Proxmox
- Provider version (ideally it should be the latest version): 0.40.0
- Terraform version: 1.5.7
- OS (where you run Terraform from): macOS 14.2
- Debug logs (`TF_LOG=DEBUG terraform apply`):

2023-12-17T16:17:33.636+0100 [DEBUG] provider.terraform-provider-proxmox_v0.40.0: google.golang.org/grpc.(*Server).processUnaryRPC(0x140002681e0, {0x105094d88, 0x140003f6150}, {0x10509a8d0, 0x140005024e0}, 0x140001ba000, 0x140003f6e70, 0x10566ccd8, 0x0)
2023-12-17T16:17:33.636+0100 [DEBUG] provider.terraform-provider-proxmox_v0.40.0: 	google.golang.org/grpc@v1.59.0/server.go:1343 +0xb8c
2023-12-17T16:17:33.636+0100 [DEBUG] provider.terraform-provider-proxmox_v0.40.0: google.golang.org/grpc.(*Server).handleStream(0x140002681e0, {0x10509a8d0, 0x140005024e0}, 0x140001ba000)
2023-12-17T16:17:33.636+0100 [DEBUG] provider.terraform-provider-proxmox_v0.40.0: 	google.golang.org/grpc@v1.59.0/server.go:1737 +0x988
2023-12-17T16:17:33.636+0100 [DEBUG] provider.terraform-provider-proxmox_v0.40.0: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-12-17T16:17:33.636+0100 [DEBUG] provider.terraform-provider-proxmox_v0.40.0: 	google.golang.org/grpc@v1.59.0/server.go:986 +0x88
2023-12-17T16:17:33.636+0100 [DEBUG] provider.terraform-provider-proxmox_v0.40.0: created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 52
2023-12-17T16:17:33.636+0100 [DEBUG] provider.terraform-provider-proxmox_v0.40.0: 	google.golang.org/grpc@v1.59.0/server.go:997 +0x160
2023-12-17T16:17:33.638+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/bpg/proxmox/0.40.0/darwin_arm64/terraform-provider-proxmox_v0.40.0 pid=12582 error="exit status 2"
2023-12-17T16:17:33.638+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-12-17T16:17:33.638+0100 [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-12-17T16:17:33.650+0100 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-12-17T16:17:33.650+0100 [ERROR] vertex "proxmox_virtual_environment_vm.dual_disk_vm[\"dc01\"]" error: Plugin did not respond
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v0.40.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104ceff38]

goroutine 56 [running]:
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmReadCustom({0x105094e30, 0x140001d9500}, 0x14000730c80, {0x104fdcc00?, 0x140000e3800?}, 0x0?, 0x14000429200, 0x0?)
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:4137 +0xb5b8
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmRead({0x105094e30, 0x140001d9500}, 0x14000730c80, {0x104fdcc00?, 0x140000e3800?})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:3789 +0x650
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmCreateStart({0x105094e30, 0x140001d9500}, 0x14000730c80, {0x104fdcc00?, 0x140000e3800?})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:2997 +0x520
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmCreateClone({0x105094e30, 0x140001d9500}, 0x1056799a0?, {0x104fdcc00?, 0x140000e3800})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:2411 +0x3a40
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmCreate({0x105094e30, 0x140001d9500}, 0x0?, {0x104fdcc00, 0x140000e3800})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:1646 +0x70
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x14000357260, {0x105094d88, 0x14000684210}, 0xd?, {0x104fdcc00, 0x140000e3800})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:778 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000357260, {0x105094d88, 0x14000684210}, 0x1400011c820, 0x14000730b00, {0x104fdcc00, 0x140000e3800})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:909 +0x860
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000123530, {0x105094d88?, 0x140003f7fb0?}, 0x14000690460)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1072 +0xb08
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x10509c218?, 0x14000123530?}}, {0x105094d88, 0x140003f7fb0}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x105094dc0?, {0x105094d88?, 0x140003f7cb0?}, 0x14000690410)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x1400026b900, {0x105094d88?, 0x140003f64b0?}, 0x140001d8000)
	github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:857 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1050552c0?, 0x1400026b900}, {0x105094d88, 0x140003f64b0}, 0x14000730000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002681e0, {0x105094d88, 0x140003f6150}, {0x10509a8d0, 0x140005024e0}, 0x140001ba000, 0x140003f6e70, 0x10566ccd8, 0x0)
	google.golang.org/grpc@v1.59.0/server.go:1343 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140002681e0, {0x10509a8d0, 0x140005024e0}, 0x140001ba000)
	google.golang.org/grpc@v1.59.0/server.go:1737 +0x988
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.59.0/server.go:986 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 52
	google.golang.org/grpc@v1.59.0/server.go:997 +0x160

Error: The terraform-provider-proxmox_v0.40.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2023-12-17T16:17:33.658+0100 [DEBUG] provider: plugin exited

**Comment by edwarddijk** [comment]
A workaround is setting a IDE interface for the CloudInit drive.

**Comment by bpg** [comment]
Hi @edwarddijk! 👋🏼 

I believe you've encountered the same issue as #796. Your cloud-init drive is likely on `local` or another storage of directory type.

I'm closing this ticket for now, feel free to reopen if you can reproduce it with the next provider version.
